// <auto-generated />
namespace UniversityManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class cngDesignation01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cngDesignation01));
        
        string IMigrationMetadata.Id
        {
            get { return "201509072149435_cngDesignation01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
